### ISSUE TITLE
Cpu and memory values are missing for lxd

### ISSUE THREAD

**Issue by sbkoto** [glpi-project/glpi-agent#488]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

Cpu and memory values are missing for lxd:

```
glpi-inventory --partial virtualmachine --debug --debug 

[debug] Running GLPI::Agent::Task::Inventory::Virtualization
[debug] Running GLPI::Agent::Task::Inventory::Virtualization::Lxd
[debug2] executing lxc list
[debug2] executing lxc info maas-rackd-01
[debug2] executing lxc config show maas-rackd-01
[debug2] executing lxc file pull maas-rackd-01/etc/machine-id -
[debug] Running GLPI::Agent::Task::Inventory::Vmsystem
[debug2] executing /sbin/sysctl -n security.jail.jailed
[debug] inventory format: Removing VIRTUALMACHINES MEMORY value as not of integer type: '16GiB'

      "virtualmachines": [
         {
            "name": "maas-rackd-01",
            "status": "running",
            "uuid": "6169c30a7d81d6f08ad289285d29cdd0e992cb78",
            "vcpu": 0,
            "vmtype": "lxd"
         }
```

### To reproduce

for lxd: glpi-inventory --partial virtualmachine --debug

### Expected behavior

:(

### Operating system

Linux

### GLPI Agent version

Nightly build (git version in additional context below)

### GLPI version

10.0.9

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.2.3

### Additional context

GLPI-Agent_v1.6-git3a55154f

**Comment by g-bougard** [comment]
Hi @sbkoto 
as you should have seen, the retrieved memory was found in an unexpected format:
```
[debug] inventory format: Removing VIRTUALMACHINES MEMORY value as not of integer type: '16GiB'
```

Can you share the output of `lxc config show maas-rackd-01` ?

**Comment by sbkoto** [comment]
> Hi @sbkoto as you should have seen, the retrieved memory was found in an unexpected format:
> 
> ```
> [debug] inventory format: Removing VIRTUALMACHINES MEMORY value as not of integer type: '16GiB'
> ```
> 
> Can you share the output of `lxc config show maas-rackd-01` ?

```
lxc config show maas-rackd-01
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Ubuntu focal amd64 (20230808)
  image.os: Ubuntu
  image.release: focal
  image.serial: "20230808"
  image.type: disk-kvm.img
  image.variant: cloud
  limits.cpu: "4"
  limits.memory: 16GiB
...
...
```
